### ISSUE TITLE
A Single 'Drawing' Can Consist of Multipolygons

### ISSUE THREAD

**Issue by dnseminara** [MidAtlanticPortal/mp-drawing#1]
- [x] Validate drawing as poly or multipoly (no points or lines)
- [x] add 'Add shape' button to step 1
- [x] add text explaining button
- [x] Deactivate buttons on selection of edit or add
- [x] Hide 'done editing' panel unless editing
- [x] Show drawing instructions when drawing additional polygons

**Comment by rhodges** [comment]
- Button text: 'Add Shape'
- Option text: 'Click **Add Shape** if you would like to add more shapes to your drawing (multipolygon)'
- Blurb text: TBD

**Comment by rhodges** [comment]
TODO: Still need to make adding shapes to previously saved drawings sensible. Stop assuming so much on 'done editing' or even on 'edit'.

**Comment by rhodges** [comment]
Disable Edit button when drawing new shape on old drawing using 
`elf.polygonLayer.features[0].state == null` or
`elf.polygonLayer.features[0].state == "Insert"`
